### ISSUE TITLE
Release the latest code

### ISSUE THREAD

**Issue by dciancu** [borayazilim/rowsorter#7]
Hello,
I find the onDragEnd event really useful.
I know I can just the download the latest version, but I like getting it versioned through bower.
Can you please make a release with the latest code?
Thank you and happy new year!

**Comment by arteyazilim** [comment]
bower.json updated with new release v2.1.1

**Comment by dciancu** [comment]
Thank you very much!
Great package!

**Comment by dciancu** [comment]
I think the package.json should be updated too.
